const resources = {
    landing: {
        SereneStay: "Serene Stay",
        subtitle: "Descoperă Camerele Și Apartamentele Noastre",
        saIncepem: "Să începem",
    },
    admin: {
        admin: "Admin",
        reservations: "Rezervări",
        rooms: "Camere",
        addRoom: "Adaugă cameră",
        users: "Utilizatori",
        reports: "Rapoarte",
        adminPage: "Pagină de admin",
        reservationsError: "Nu s-au putut încărca rezervările.",
        roomDeactivated: "Camera a fost dezactivată cu succes",
        somethingWentWrong: "Ceva nu a mers bine",
        roomActivated: "Camera a fost activată cu succes",
        active: "Activă",
        inactive: "Inactivă",
        couldntLoadRooms: "Nu s-au putut încărca camerele.",
        failedToFetchUsers: "Failed to fetch users:",
        failedToFetchRooms: "Failed to fetch rooms:",
        failedToFetchBookings: "Failed to fetch bookings:",
        couldntLoadUsers: "Nu s-au putut încărca utilizatorii.",
        users: "Utilizatori",
        userId: "Id utilizator",
        name: "Nume",
        mail: "Mail",
        noUsers: "Nu există utilizatori.",
        rentPerDayError: "Prețul pe zi trebuie să fie un număr pozitiv.",
        maxcountError: "Capacitatea trebuie să fie un număr întreg pozitiv.",
        priceError: "Prețul pe noapte este obligatoriu.",
        capacityError: "Capacitatea este obligatorie.",
        congrats: "Felicitări",
        roomAdded: "Cameră adăugată cu succes",
        oops: "Oops",
        somethingWentWrong: "Ceva nu a mers bine",
        roomName: "Denumire cameră",
        pricePerDay: "Preț pe noapte",
        capacity: "Capacitate",
        description: "Descriere",
        urlImage: "URL imagine",
        success: "Success",
        delux: "Delux",
        standard: "Standard",
        bookingId: "Id rezervare",
        room: "Cameră",
        from: "De la",
        to: "Până la",
        status: "Status",
        roomId: "Id cameră",
        type: "Tip",
        actions: "Acțiuni",
        noRooms: "Nu există camere.",
        totalRooms: "camere în total",
        totalBookings: "rezervări în total"
    },

    booking: {
        failedToFetchRoomDetails: "Failed to fetch room details:",
        bookingSuccesful: "Booking successful:",
        roomBooked: "Camera a fost rezervata cu succes",
        bookingFailed: "Rezervarea a eșuat:",
        user: "Utilizator",
        checkIn: "Check-In",
        checkOut: "Check-Out",
        numberOfNights: "Număr de nopți",
        pricePerNight: "Preț pe noapte",
        totalValue: "Valoare totală",
        toPayment: "Spre plată",
        noPreviousBookings: "Nu există sesiuni de cazare anterioare.",
        rawData: "Raw data from API:",
        invalidDateValue: "Invalid date value:",
        failedToCheckAvailability: "Failed to check availability:",
        failedToBlockDates: "Failed to block dates:",
        selectRoom: "Selectează o cameră",
        select: "Selectează camera:",
        errorChecking: "Eroare la verificarea disponibilității.",
        blockDates: "Blochează datele"

    },

    home: {
        roomType: "tip cameră",
        sort: "Sortare preț",
        descending: "Descrescător",
        ascending: "Crescător",
        maxCapacity: "capacitate maximă",
        roomSearch: "căutare cameră"
    },

    login: {
        result: "Login Result:",
        invalidData: "Date invalide",
        connect: "Conectare",
        password: "Parolă",
        noAccount: "Nu ai cont?",
        registerHere: "Înregistrează-te aici",
        emptyName: "Numele nu poate fi vid.",
        invalidMail: "Mail invalid.",
        shortPassword: "Parola trebuie să aibă cel puțin 6 caractere.",
        usedMail: "Există deja un cont cu acest email.",
        mailVerificationError: "Eroare la verificarea mailului:",
        mailError: "A apărut o eroare. Vă rugăm să încercați din nou.",
        signUpError: "A apărut o eroare la înregistrare. Vă rugăm să încercați din nou.",
        passwordsNotMatching: "Parolele nu corespund",
        signUpSuccessfully: "Înregistrare efectuată cu succes!",
        signUp: "Înregistrare",
        confirmPassword: "Confirmare parolă",
        haveAccount: "Ai deja cont?",
        connectHere: "Conectează-te aici",
        logIn: "Conectare"
    },

    profile: {
        myProfile: "Profilul meu",
        yes: "DA",
        no: "NO",
        history: "Jurnal de cazări",
        bookings: "Rezervări",
        canNotCancel: "Nu se poate anula",
        tooLate: "Rezervarea poate fi anulată doar cu minim 5 zile înainte.",
        bookingCanceled: "Rezervare anulată cu succes",
        allReservations: "Toate rezervările",
        previousBookings: "Rezervări anterioare",
        futureBookings: "Rezervări viitoare",
        canceledBookings: "Rezervări anulate",
        bookingId: "Id Rezervare",
        total: "Total de plată",
        cancel: "ANULEAZĂ REZERVAREA",
        confirmed: "Rezervare confirmată",
        canceled: "Rezervare anulată",
        canNotLoadBookings: "Cannot load bookings",
        ron: "RON"
    },

    reports: {
        errorFetchingRoomBookingsReport: "Error fetching room bookings report:",
        errorFetchingBookingsByMonthReport: "Error fetching bookings by month report:",
        reportByBookings: "Raport după numărul de rezervări",
        bookings: "Rezervări",
        reportByNights: "Raport după numărul de nopți",
        nights: "Nopți",
        noDates: "Nu există date pentru luna selectată.",
    },

    rooms: {
        details: "Detalii",
        book: "Rezervă",
        close: "Închideți"
    }

};

export default resources;